# Generated by Django 6.0.4 on 2026-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=200)),
                ('lead_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('trend', models.CharField(max_length=50)),
                ('signal', models.CharField(max_length=50)),
                ('action', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('eta', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=50)),
                ('carrier', models.CharField(max_length=100)),
                ('delay_reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
